package com.example.demo.entity;


import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;
import java.util.Date;

/**
 * Created on 04.08.2021
 *
 * @author roland
 **/
@Entity
@Data
public class Book2User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @ApiModelProperty("link createion time")
    private Date time;

    @ApiModelProperty("foreign key on table book_user_types")
    @Column(name="id_type")
    private Integer idType;

    @ApiModelProperty("foreign key on table books")
    @Column(name="id_book")
    private Integer idBook;

    @ApiModelProperty("foreign key on table users")
    @Column(name="id_user")
    private Integer idUser;

}
