package com.example.demo.entity;


import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

/**
 * Created on 04.08.2021
 *
 * @author roland
 **/
@Entity
public class Book2User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Getter
    @Setter
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Getter
    @Setter
    @ApiModelProperty("link createion time")
    private Date time;

    @Getter
    @Setter
    @ApiModelProperty("foreign key on table book_user_types")
    //FIXME CamelCase
    private Integer id_type;

    @Getter
    @Setter
    @ApiModelProperty("foreign key on table books")
    //FIXME CamelCase
    private Integer id_book;

    @Getter
    @Setter
    @ApiModelProperty("foreign key on table users")
    //FIXME CamelCase чтобы колонка сохранялась под нужным именем используйте @Column(name="")
    private Integer id_user;

}
