package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

/**
 * Created on 02.08.2021
 *
 * @author roland
 **/
@Entity
public class Book2Genre {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Getter
    @Setter
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Getter
    @Setter
    @ApiModelProperty("foreign key for table books")
    @Column(name="id_book")
    private int idBook;

    @Getter
    @Setter
    @ApiModelProperty("foreign key for table genres")
    @Column(name="id_genre")
    private int idGenre;
}
