package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Created on 13.09.2021
 *
 * @author roland
 **/

@Entity
@Data
public class Book2user_type {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @ApiModelProperty("id generated by db automatically")
    private int id;

    private String code;

    private String name;
}

