package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Created on 02.08.2021
 *
 * @author roland
 **/
@Entity
public class Book2Genre {
    private final static Logger log = LoggerFactory.getLogger(Book2Genre.class);
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Getter
    @Setter
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Getter @Setter
    @ApiModelProperty("foreign key for table books")
    private int id_book;

    @Getter @Setter
    @ApiModelProperty("foreign key for table genres")
    private int id_genre;
}
