package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;

/**
 * Created on 18.08.2021
 *
 * @author roland
 **/
@Entity
@Data
@Table(name="book2author")
public class Book2Author {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @ApiModelProperty("foreign key for table books")
    @Column(name="id_book")
    private int idBook;

    @ApiModelProperty("foreign key for table authors")
    @Column(name="id_author")
    private int idAuthor;

    @Column(name="sort_index")
    private int sortIndex;
}
