package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;
import java.util.Date;

/**
 * Created on 16.08.2021
 *
 * @author roland
 **/
@Entity
@Data
@Table(name="book_review_like")
public class BookReviewLike {

    @Id
    @SequenceGenerator( name = "bookReviewLikeSequence", sequenceName = "BOOK_REVIEW_LIKE_SEQ", allocationSize = 1, initialValue = 5000)
    @GeneratedValue( strategy = GenerationType.SEQUENCE, generator = "bookReviewLikeSequence")
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Column(name="id_review")
    @ApiModelProperty("foreign key on table book_review")
    private int idReview;

    @Column(name="id_user")
    @ApiModelProperty("foreign key on table users")
    private int idUser;

    @ApiModelProperty("time of creation book review like/dislike")
    private Date time;

    @ApiModelProperty("like/dislike of book review")
    private short value;

//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "id_review", insertable = false, updatable = false)
//    private BookReview ratedBookReview;

//    @ManyToOne
//    @JoinColumn(name = "id_review", referencedColumnName = "id", insertable = false, updatable = false)
//    @JsonIgnore
//    private BookReview bookReview;

}
