package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

/**
 * Created on 31.07.2021
 *
 * @author roland
 **/
@Entity
public class Book2Tag {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Getter
    @Setter
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Getter
    @Setter
    @Column(name="id_book")
    private int idBook;

    @Getter
    @Setter
    @Column(name="id_tag")
    private int idTag;
}
