package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Created on 04.08.2021
 *
 * @author roland
 **/

@Entity
public class BookPopular {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Getter
    @Setter
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Getter @Setter
    @ApiModelProperty("foreign key on table books")
    private Integer id_book;

    @Getter @Setter
    @ApiModelProperty("index of book popular`s")
    private float popular;
}
