package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;
import java.util.Date;

/**
 * Created on 16.08.2021
 *
 * @author roland
 **/
@Entity
@Data
@Table(name="book_review_like")
public class BookReviewLike {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Column(name="id_review")
    @ApiModelProperty("foreign key on table book_review")
    private int idReview;

    @Column(name="id_user")
    @ApiModelProperty("foreign key on table users")
    private int idUser;

    @ApiModelProperty("time of creation book review like/dislike")
    private Date time;

    @ApiModelProperty("like/dislike of book review")
    private short value;

}
