package com.example.demo.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;
import java.util.Date;

/**
 * Created on 16.08.2021
 *
 * @author roland
 **/
@Entity
@Table(name = "book_review")
@ApiModel(description = "entity representing a review of book")
@Data
public class BookReview {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Column(name="id_book")
    @ApiModelProperty("foreign key on table books")
    private int idBook;

    @Column(name="id_user")
    @ApiModelProperty("foreign key on table users")
    private int idUser;

    @ApiModelProperty("time of creation book review")
    private Date time;

    @Column(columnDefinition="TEXT")
    private String text;
}
