package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;
import java.util.Date;

/**
 * Created on 15.08.2021
 *
 * @author roland
 **/
@Entity
@Data
@Table(name="book_user_rating")
public class BookUserRating {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @ApiModelProperty("time of rating")
    private Date time;

    @ApiModelProperty("foreign key on table books")
    @Column(name="id_book")
    private Integer idBook;

    @ApiModelProperty("foreign key on table users")
    @Column(name="id_user")
    private Integer idUser;

    @ApiModelProperty("book rating by user")
    private Integer rate;
}
