package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * Created on 02.08.2021
 *
 * @author roland
 **/
@Entity
@Data
@Table(name = "genres")
public class Genre {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)


    @ApiModelProperty("id generated by db automatically")
    private int id;



    @ApiModelProperty("id of parent genre")
    @Column(name="id_parent")
    private Integer idParent;



    @ApiModelProperty("mnemonical identifier of genre")
    private String slug;



    @ApiModelProperty("genre name")
    private String name;

    public Genre() {
        this.childs = null;
    }

    @Transient


    private List<Genre> childs;

    @Transient
    public void addChild(Genre childGenre) {
        if (childs == null) {
            childs = new ArrayList<>();
        }
        childs.add(childGenre);
    }


    @ManyToMany
    @JoinTable(
            name = "book2genre",
            joinColumns = @JoinColumn(name = "id_genre"),
            inverseJoinColumns = @JoinColumn(name = "id_book"))
    private Set<Book> genredBooks;
}
