package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * Created on 02.08.2021
 *
 * @author roland
 **/
@Entity
@Table(name = "genres")
public class Genre {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Getter
    @Setter
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Getter
    @Setter
    @ApiModelProperty("id of parent genre")
    //FIXME поле nullable = true идет по умолчанию
    @Column(nullable = true) //не задает ограничение на поле not null
    //FIXME CamelCase
    private Integer id_parent;

    @Getter
    @Setter
    @ApiModelProperty("mnemonical identifier of genre")
    private String slug;

    @Getter
    @Setter
    @ApiModelProperty("genre name")
    private String name;

    @Transient
    @Getter
    @Setter
//FIXME инициализация переменных должна быть в конструкторе
    private List<Genre> childs = null;

    @Transient
    public void addChild(Genre childGenre) {
        if (childs == null) {
            childs = new ArrayList<>();
        }
        childs.add(childGenre);
    }

    @Getter
    @ManyToMany
    @JoinTable(
            name = "book2genre",
            joinColumns = @JoinColumn(name = "id_genre"),
            inverseJoinColumns = @JoinColumn(name = "id_book"))
    //FIXME еще один пример не защищенной переменной
    Set<Book> genredBooks;
}
