package com.example.demo.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Set;

/**
 * Created on 31.07.2021
 *
 * @author roland
 **/
@Entity
@Table(name="tags")
public class Tag {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Getter
    @Setter
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Getter @Setter
    private String tagName;

    @Getter
    @ManyToMany
    @JoinTable(
            name = "book2tag",
            joinColumns = @JoinColumn(name = "id_tag"),
            inverseJoinColumns = @JoinColumn(name = "id_book"))
    Set<Book> taggedBooks;

    @Transient
    public String tagClassName(int classLength) {
        switch (taggedBooks.size() / classLength) {
            case 0: return "Tag_xs";
            case 1: return "Tag_sm";
            case 2: return "Tag_md";
            default: return "Tag_lg";
        }
    }

    @Transient
    public String tagHidden() {
        return taggedBooks.isEmpty() ? "display:none" : "";
    }
}
